services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: MAX_CHATBOT/Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    disk:
      name: pdfs
      mountPath: /app/pdfs
      sizeGB: 1

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: MAX_CHATBOT/price-whisperer-bot/Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: ""