services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: MAX_CHATBOT/Dockerfile
    buildContext: MAX_CHATBOT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: MAX_CHATBOT/price-whisperer-bot/Dockerfile
<<<<<<< HEAD
    buildContext: MAX_CHATBOT/price-whisperer-bot
    autoDeploy: true
=======
    autoDeploy: true
>>>>>>> 22cae0df92302a29c17a068baf6ad07330bd74ec
