services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: MAX_CHATBOT/Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: MAX_CHATBOT/price-whisperer-bot/Dockerfile
    autoDeploy: true
