// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqypzvcdpusejlovwhjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxeXB6dmNkcHVzZWpsb3Z3aGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzc3MzUsImV4cCI6MjA2NTcxMzczNX0.wmPzS_gqJPPHZwJcT5ZzbsvY_4Zr8Gniiu9EBcA8wJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);